In [20]:
import numpy as np

In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 9], [4, 5, 6, 7]])

In [22]:
print(arr1[0])  # Output: 1
print(arr2[1, 2])  # Output: 6

1
6


In [23]:
arr1[0] = 10
print(arr1)  # Output: [10, 2, 3, 4, 5]

[10  2  3  4  5]


In [26]:
# Array indexing and slicing
print(arr1[1:4])  # Output: [2, 3, 4]
print(arr2[:, 1:])  # Output: [[2, 3, 9], [5, 6, 7]]

[2 3 4]
[[2 3 9]
 [5 6 7]]


In [27]:
arr3 = arr1 + 5
print(arr3)  # Output: [15, 7, 8, 9, 10]

[15  7  8  9 10]


In [28]:
arr4 = arr1 * arr3
print(arr4) 

[150  14  24  36  50]


In [29]:
# Array aggregation and statistical operations
print(np.sum(arr2))  # Output: 37
print(np.mean(arr2))  # Output: 4.625
print(np.max(arr2))  # Output: 9

37
4.625
9


In [14]:
# Working with multi-dimensional arrays
arr5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [15]:
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# Universal functions in NumPy
print(np.sqrt(arr1))  # Output: [3.16227766, 1.41421356, 1.73205081, 2., 2.23606798]
print(np.exp(arr1))  # Output: [22026.4657948, 7.3890561, 20.08553692, 54.59815003, 148.4131591]

[3.16227766 1.41421356 1.73205081 2.         2.23606798]
[2.20264658e+04 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02]
